"""empty message

Revision ID: 246db17ff3bc
Revises: 767e9fb8ca9c
Create Date: 2021-04-27 14:49:50.045415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "246db17ff3bc"
down_revision = "767e9fb8ca9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("date_end", sa.Date(), nullable=True))
    op.add_column("course", sa.Column("date_start", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "date_start")
    op.drop_column("course", "date_end")
    # ### end Alembic commands ###
