"""empty message

Revision ID: 2719f8dfddc8
Revises: b377b526c581
Create Date: 2021-05-03 17:40:18.167149

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2719f8dfddc8"
down_revision = "b377b526c581"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sign_in_task", sa.Column("title", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sign_in_task", "title")
    # ### end Alembic commands ###
