"""empty message

Revision ID: 45211d39108b
Revises: 2e393e48f4c4
Create Date: 2021-05-03 16:52:34.180543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45211d39108b"
down_revision = "2e393e48f4c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sign_in_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sign_in_task_record",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["sign_in_task.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "student_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sign_in_task_record")
    op.drop_table("sign_in_task")
    # ### end Alembic commands ###
