"""empty message

Revision ID: 7a3be7076062
Revises: a335cddf8c21
Create Date: 2021-05-19 16:35:02.831487

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7a3be7076062"
down_revision = "a335cddf8c21"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("cover", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "cover")
    # ### end Alembic commands ###
