"""empty message

Revision ID: 7e5fe49eee83
Revises: 54a8488131c3
Create Date: 2021-04-28 13:48:51.454277

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e5fe49eee83"
down_revision = "54a8488131c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
