"""empty message

Revision ID: a335cddf8c21
Revises: 5f00836ba009
Create Date: 2021-05-19 15:52:03.384312

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a335cddf8c21"
down_revision = "5f00836ba009"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attachment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("original_filename", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["course_section.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("file")
    op.drop_column("course_section", "attachments")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course_section",
        sa.Column(
            "attachments",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "file",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="file_pkey"),
    )
    op.drop_table("attachment")
    # ### end Alembic commands ###
