"""empty message

Revision ID: b377b526c581
Revises: 45211d39108b
Create Date: 2021-05-03 16:59:32.278142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b377b526c581"
down_revision = "45211d39108b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sign_in_task", sa.Column("time_end", sa.DateTime(), nullable=True))
    op.add_column("sign_in_task", sa.Column("time_start", sa.DateTime(), nullable=True))
    op.drop_column("sign_in_task", "date_start")
    op.drop_column("sign_in_task", "date_end")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sign_in_task",
        sa.Column("date_end", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "sign_in_task",
        sa.Column("date_start", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_column("sign_in_task", "time_start")
    op.drop_column("sign_in_task", "time_end")
    # ### end Alembic commands ###
